### ISSUE TITLE
Improved Errors

### ISSUE THREAD

**Issue by Lugoues** [neosmart/securestore-rs#2]
The error type does not fully implement `Box<dyn std::error::Error + Send + Sync + 'static>` and causes some libraries like anyhow to not work with the `?` operator.

```
(dyn std::error::Error + 'static)` cannot be sent between threads safely
the trait `std::marker::Send` is not implemented for `(dyn std::error::Error + 'static)`
required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
required because it appears within the type `std::option::Option<std::boxed::Box<(dyn std::error::Error + 'static)>>`
required because it appears within the type `securestore::errors::Error`
required because of the requirements on the impl of `std::convert::From<securestore::errors::Error>` for `anyhow::Error`
required by `std::convert::From::from`rustc(E0277)
```

**Comment by mqudsi** [comment]
Thanks for filing. It seems to be that most libraries are fine requiring their error types to be `Send + Sync` in addition to `'static`. I've made the change but I hope that it's not going to cause any problems for us down the line.

Let me sleep on it and then if it sits OK with me I'll push out an update. It should be a strictly backwards compatible change, so we can just increment the minor version.

**Comment by mqudsi** [comment]
I just pushed out SecureStore 0.99.3 with the improvements to the error type from 3a15fa1. There are no other changes.
