### ISSUE TITLE
Struggling to create a Rust Project that can be called from a SiteSpeed test (javascript)

### ISSUE THREAD

**Issue by Myvryn-LF** [neosmart/securestore-rs#5]
Hello, I've been struggling all day trying to create a rust project that would allow me to grab passwords from a secrets.json file. I've been trying to build using many methods, but every time I do, I see an error telling me that the build "failed to run custom build command for 'openssl-sys v0.9.100'". 

At this point, the "that can be called from a SiteSpeed test" is irrelevant as I can't get the project to build. But I thought I'd leave it in there on the chance that knowing what I'm **_trying_** to accomplish might enable you to tell me how best to proceed.

**CAVEAT**:  I am brand new to rust... Today is the first time I've ever touched it, so my question might be pretty basic. (I'm really hoping it just an "Oh I'm an idiot" moment here).

I am running on a linux (ubuntu) box with OpenSSL v0.10.64 installed.

**My Cargo.toml file looks like this:**
```
[package]
name = "secure_password_helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
securestore = "0.100.0"
openssl = { version = "0.10.64", features = ["vendored"] }
wasm-bindgen = "0.2.91"

[lib]
crate-type = ["cdylib", "rlib"]
```

I've tried changing the openssl entry to 0.9.100, but that just fails altogether.

**I get the "failed to run custom build" when I attempt to build with any of the following commands:**
_cargo build
cargo build --target wasm32-unknown-unknown_

(it looks like this method calls cargo build in the background)
_wasm-pack build
wasm-pack build --target nodejs_

_wasm-bindgen (anything)_
requires that I point it at a wasm file, which I have been unable to generate.

**I have tried to create rust projects using the following commands, all with the same outcome:**
_cargo new --lib <project_name>
cargo new <project_name>_

Like I said, I'm brand new to rust and I'm really hoping that I'm just missing something obvious here.

**Comment by Myvryn-LF** [comment]
I figured out that it was much easier to build a Rust Project that could be called from a BASH script, which then feeds my password into the SiteSpeed.io tests.

Using this method also allows me to use secrets.json files that are mounted on a network (windows) drive. I wasn't able to do that from a command line in linux without wiping out the entire contents of the secrets file.

**Comment by mqudsi** [comment]
Glad you found a workaround. I don't think it's anything you did wrong, I'm pretty sure the problem is with building openssl for wasm.

The solution you ended up with makes more sense to me, fwiw.
